cdef extern from "Python.h":
    void PyErr_Clear()
